export const GET_ALL_PROJECTS_REQUEST = 'GET_ALL_PROJECTS_REQUEST'
export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS'
export const GET_ALL_PROJECTS_FAIL = 'GET_ALL_PROJECTS_FAIL'


export const ADD_PROJECT_REQUEST = 'ADD_PROJECT_REQUEST'
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const ADD_PROJECT_FAIL = 'ADD_PROJECT_FAIL'
export const ADD_PROJECT_RESET = 'ADD_PROJECT_RESET'




export const DETAIL_PROJECT_REQUEST = 'DETAIL_PROJECT_REQUEST'
export const DETAIL_PROJECT_SUCCESS = 'DETAIL_PROJECT_SUCCESS'
export const DETAIL_PROJECT_FAIL = 'DETAIL_PROJECT_FAIL'



export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST'
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS'
export const UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL'
export const UPDATE_PROJECT_RESET = 'UPDATE_PROJECT_RESET'



export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL'

